[package]
name = "icrc3-mo"
version = "0.3.5"
description = "icrc3 for motoko"
repository = "https://github.com/PanIndustrial-Org/icrc3.mo"
keywords = [ "ledger", "transactions", "log" ]
license = "MIT"

[dependencies]
base = "0.14.14"
vector = "0.4.1"
sha2 = "0.1.4"
rep-indy-hash = "0.1.1"
class-plus = "0.0.1"
ic-certification = "0.1.3"
map = "9.0.1"
stable-write-only = "0.1.1"

[dev-dependencies]
test = "1.2.0"
fuzz = "0.2.0"
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0@3dac8a071b69e4e651b25a7d9683fe831eb7cffd"

[toolchain]
moc = "0.14.14"